# Generated by Django 5.1.2 on 2024-10-23 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_tweetbox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='image',
        ),
        migrations.CreateModel(
            name='TweetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tweets/')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_tweetbox.tweet')),
            ],
        ),
    ]
