# Generated by Django 5.1.2 on 2024-10-23 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_tweetbox', '0002_remove_tweet_image_tweetimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetimage',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='a_tweetbox.tweet'),
        ),
    ]
