# Generated by Django 5.1.2 on 2024-10-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_tweetbox', '0003_alter_tweetimage_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.TextField(max_length=280),
        ),
    ]
